### PR TITLE
ridgebot: New APP - ridgebot-splunk connector help customer to manage…

### PR DESCRIPTION
**Pull request by ridgesecurity**
… ridgebot automated penetration test and retrieve the results

ridgebot: New APP - ridgebot-splunk connector help customer to manage ridgebot automated penetration test and retrieve the results

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ x] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ x] Verify all checks are passing.
- [ x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- [x]Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ridgesecurity** [comment]
Hi, 

Got following Static Tests errors, need your suggestion on remediation.
Output:  /builds/phantom/results/app_test.xml
{
    "FAILED": {
        "CRITICAL": [
            {
                "App Actions": {
                    "message": "Some action names were unknown",
                    "success": false,
                    "verbose": [
                        "Action `get data statistics` not known.",
                        "Action `cancel a task` not known.",
                        "Action `get detail task info` not known.",
                        "Action `get task info lists` not known.",
                        "Action `create report` not known. Would `create export` be better?"
                    ]
                }
            },
            {
                "File Manipulation Functions": {
                    "message": "File manipulation functions exist",
                    "success": false,
                    "verbose": [
                        "File `ridgebot_connector.py` opens this file: file_path"
                    ]
                }
            }
        ],
        "NONCRITICAL": []
    },

for Action name, it is our own definition, please provide the suggestion to change.
For file manipulation, the action provide following operation: download report from asset and save it to Vault. We download the report to tmp dir and then save it to vault. with this operation, we have to perform file manipulation, right?

**Comment by ridgesecurity** [comment]
#how can I request a code reviewer? 

#Got following Static Tests errors, need your suggestion on remediation.
Output: /builds/phantom/results/app_test.xml
{
"FAILED": {
"CRITICAL": [
{
"App Actions": {
"message": "Some action names were unknown",
"success": false,
"verbose": [
"Action get data statistics not known.",
"Action cancel a task not known.",
"Action get detail task info not known.",
"Action get task info lists not known.",
"Action create report not known. Would create export be better?"
]
}
},
{
"File Manipulation Functions": {
"message": "File manipulation functions exist",
"success": false,
"verbose": [
"File ridgebot_connector.py opens this file: file_path"
]
}
}
],
"NONCRITICAL": []
},

for Action name, it is our own definition, please provide the suggestion to change.
For file manipulation, the action provide following operation: download report from asset and save it to Vault. We download the report to tmp dir and then save it to vault. with this operation, we have to perform file manipulation, right?

**Comment by dgopani-crest** [comment]
Hello @ridgesecurity, We have added this app to our queue and will start working on this soon. 
we will take for the failures mentioned above and will reach out to you in case of any query.
Thanks!

**Comment by dgopani-crest** [comment]
Hi @ridgesecurity, We have started working on this app. we have a couple of queries

1. Can you please update the action name as suggested below:

- cancel a task -> `cancel task`
- get detail task info -> `get task info` or `get task`
- get task info lists ->` list tasks` or `list task infos`

2. Also, `cancel a task, get detail task info, get detail task info, and  create report` actions do not have any output data paths. Can you please update this
Screenshot 2022-03-23 at 2 21 52 PM

**Comment by ridgesecurity** [comment]
Deep,

I’ve changed name accordingly. Please check.

All actions has the output data paths.

Thanks,

Yvonne

***@***.***
Yvonne Ye
VP, Solution Enginerring
Ridge Security Technology Inc.
Mobile/WhatsApp +1.925.895.8212
Office   +1.408.800.6881
Email    ***@***.******@***.***>
www.ridgesecurity.ai<http://www.ridgesecurity.ai/>
[A picture containing drawing, plate  Description automatically generated]<http://linkedin.com/company/ridge-security>     [Logo, icon  Description automatically generated] <https://www.youtube.com/ridgesecurity>      [Logo, icon  Description automatically generated] <https://twitter.com/ridgesecurityai>       [A picture containing drawing  Description automatically generated] <https://www.facebook.com/RidgeBot/>


From: Deep Gopani ***@***.***>
Reply-To: splunk-soar-connectors/ridgebot ***@***.***>
Date: Wednesday, March 23, 2022 at 1:52 AM
To: splunk-soar-connectors/ridgebot ***@***.***>
Cc: Yvonne Ye ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk-soar-connectors/ridgebot] ridgebot: New APP - ridgebot-splunk connector help customer to manage… (PR #1)


Hi @ridgesecurity<https://github.com/ridgesecurity>, We have started working on this app. we have a couple of queries

  1.  Can you please update the action name as suggested below:

  *   cancel a task -> cancel task
  *   get detail task info -> get task info or get task
  *   get task info lists -> list tasks or list task infos

  1.  Also, cancel a task, get detail task info, get detail task info, and create report actions do not have any output data paths. Can you please update this

[Image removed by sender. Screenshot 2022-03-23 at 2 21 52 PM]<https://user-images.githubusercontent.com/64279254/159660165-18d0828e-9131-44b5-8ec6-6179ffc78352.png>

**Comment by dgopani-crest** [comment]
Hi @ridgesecurity, Thanks for the update. 
It looks like action names are updated but output datapaths are not added in the action? Can you please check?
The output datapath will help users to use data in playbooks.

**Comment by ridgesecurity** [comment]
Deep,

Thanks a lot. I’ve added action datapath.

Yvonne

***@***.***
Yvonne Ye
VP, Solution Enginerring
Ridge Security Technology Inc.
Mobile/WhatsApp +1.925.895.8212
Office   +1.408.800.6881
Email    ***@***.******@***.***>
www.ridgesecurity.ai<http://www.ridgesecurity.ai/>
[A picture containing drawing, plate  Description automatically generated]<http://linkedin.com/company/ridge-security>     [Logo, icon  Description automatically generated] <https://www.youtube.com/ridgesecurity>      [Logo, icon  Description automatically generated] <https://twitter.com/ridgesecurityai>       [A picture containing drawing  Description automatically generated] <https://www.facebook.com/RidgeBot/>


From: Deep Gopani ***@***.***>
Reply-To: splunk-soar-connectors/ridgebot ***@***.***>
Date: Friday, March 25, 2022 at 2:06 AM
To: splunk-soar-connectors/ridgebot ***@***.***>
Cc: Yvonne Ye ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk-soar-connectors/ridgebot] ridgebot: New APP - ridgebot-splunk connector help customer to manage… (PR #1)


Hi @ridgesecurity<https://github.com/ridgesecurity>, Thanks for the update.
It looks like action names are updated but output datapaths are not added in the action? Can you please check?
The output datapath will help users to use data in playbooks.

**Review by alexa-phantom — APPROVED** [review]

**Pull request merged**
